_: {
  # Generate lefthook.yml and rc file via files module
  perSystem =
    { pkgs, ... }:
    {
      files.files = [
        {
          path_ = "lefthook.yml";
          drv = pkgs.writeText "lefthook.yml" ''
            # Git hooks manager - https://lefthook.dev/
            # Generated by Nix - do not edit directly
            min_version: 1.10.0
            glob_matcher: doublestar

            # Source the nix develop environment (cached for speed)
            rc: ./scripts/lefthook-rc.sh

            output:
              - meta
              - summary
              - failure
              - success
              - execution
              - execution_info
              - execution_output

            pre-commit:
              parallel: true
              skip: [merge, rebase]
              fail_on_changes: ci
              # Modified/added files (staged or not) + untracked files
              files: >-
                sh -c '{ git diff --name-only HEAD 2>/dev/null;
                git ls-files --others --exclude-standard; } | sort -u'

              jobs:
                - name: validation
                  priority: 1
                  exclude:
                    - "inputs/**"
                    - "nixos-manual/**"
                  group:
                    parallel: true
                    jobs:
                      - name: check-yaml
                        tags: [validation]
                        run: yamllint -d relaxed -- {files}
                        glob: "**/*.{yaml,yml}"
                        fail_text: "Invalid YAML syntax. Check errors above."

                      - name: check-json
                        tags: [validation]
                        run: jq empty {files}
                        glob: "**/*.json"
                        fail_text: "Invalid JSON syntax. Validate with: jq . <file>"

                - name: security
                  priority: 2
                  exclude:
                    - "inputs/**"
                    - "nixos-manual/**"
                  group:
                    parallel: true
                    jobs:
                      - name: ripsecrets
                        tags: [security]
                        run: ripsecrets -- {files}
                        exclude:
                          - "modules/networking/networking.nix"
                        fail_text: >-
                          Secrets/keys detected! Remove sensitive data
                          or add to .secretsignore

                      - name: ensure-sops
                        tags: [security]
                        run: lefthook-ensure-sops {files}
                        glob: "secrets/**/*.{yaml,yml,json,env,ini,age,enc}"
                        fail_text: "Secrets must be SOPS-encrypted. Run: sops <file>"

                - name: formatting
                  priority: 3
                  exclude:
                    - "inputs/**"
                    - "nixos-manual/**"
                  group:
                    parallel: true
                    jobs:
                      - name: treefmt
                        tags: [formatting]
                        run: lefthook-treefmt
                        fail_text: >-
                          Formatting failed. Check syntax errors above,
                          then run: nix fmt

                - name: nix-linting
                  priority: 4
                  glob: "**/*.nix"
                  exclude:
                    - "inputs/**"
                    - "nixos-manual/**"
                  group:
                    parallel: true
                    jobs:
                      - name: deadnix
                        tags: [nix]
                        run: deadnix --fail -- {files}
                        fail_text: "Unused code detected. Remove dead bindings shown above."

                      - name: statix
                        tags: [nix]
                        run: lefthook-statix {files}
                        fail_text: "Nix anti-patterns found. Run: statix fix <file>"

                - name: quality
                  priority: 5
                  exclude:
                    - "inputs/**"
                    - "nixos-manual/**"
                  group:
                    jobs:
                      - name: typos
                        tags: [quality]
                        run: typos --config .typos.toml -- {files}
                        fail_text: >-
                          Typos detected. Run: typos -w <file> to fix,
                          or add to .typos.toml

                - name: custom
                  priority: 6
                  group:
                    jobs:
                      - name: managed-files-drift
                        tags: [custom]
                        run: lefthook-managed-files-drift
                        env:
                          AUTO_FIX_MANAGED: "1"
                          MANAGED_FILES_VERBOSE: "0"
                        fail_text: >-
                          Managed files out of sync.
                          Run: nix develop -c write-files

                      - name: apps-catalog-sync
                        tags: [custom]
                        run: lefthook-apps-catalog-sync
                        fail_text: >-
                          apps-enable.nix out of sync with modules/apps/.
                          See errors above.
          '';
        }
        {
          path_ = "scripts/lefthook-rc.sh";
          drv = pkgs.writeText "lefthook-rc.sh" ''
            # Lefthook RC file - sets up nix develop PATH for hooks
            # Generated by Nix - do not edit directly

            # Skip if already in nix shell (fast path)
            if [ -n "''${IN_NIX_SHELL:-}" ]; then
              return 0 2>/dev/null || true
            fi

            CACHE_DIR=".git/lefthook-cache"
            CACHE_FILE="$CACHE_DIR/path.sh"
            HASH_FILE="$CACHE_DIR/flake.lock.hash"

            mkdir -p "$CACHE_DIR" 2>/dev/null || true

            # Compute hash of flake.lock
            current_hash=""
            if [ -f "flake.lock" ]; then
              current_hash=$(sha256sum flake.lock 2>/dev/null | cut -d' ' -f1)
            fi

            # Check if cache is valid
            needs_update=1
            if [ -f "$CACHE_FILE" ] && [ -f "$HASH_FILE" ]; then
              cached_hash=$(cat "$HASH_FILE" 2>/dev/null || echo "")
              if [ "$current_hash" = "$cached_hash" ] && [ -n "$current_hash" ]; then
                needs_update=0
              fi
            fi

            # Generate cache if needed (slow first time, fast after)
            if [ "$needs_update" = "1" ]; then
              echo "Generating lefthook environment cache..." >&2
              # Extract only PATH from nix develop (POSIX-compatible)
              nix_path=$(nix develop --accept-flake-config -c sh -c 'echo "$PATH"' 2>/dev/null)
              if [ -n "$nix_path" ]; then
                echo "export PATH=\"$nix_path\"" > "$CACHE_FILE"
                echo "$current_hash" > "$HASH_FILE"
                echo "Cache generated: $CACHE_FILE" >&2
              else
                echo "Warning: Failed to generate cache, hooks may fail outside devshell" >&2
                return 0 2>/dev/null || true
              fi
            fi

            # Source the cached PATH
            if [ -f "$CACHE_FILE" ]; then
              . "$CACHE_FILE"
            fi
          '';
        }
      ];
    };
}
