#!/usr/bin/env bash
# shellcheck shell=bash
# update-librewolf-ubo-lists.sh - refresh the generated uBO list selection
# from LibreWolf's upstream asset catalog.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

DEFAULT_SOURCE_URL="https://codeberg.org/librewolf/source/raw/branch/main"
DEFAULT_SOURCE_URL+="/assets/uBOAssets.json"
DEFAULT_OUTPUT_PATH="${REPO_ROOT}/modules/browsers"
DEFAULT_OUTPUT_PATH+="/_librewolf-ubo-default-lists.json"

SOURCE_URL="${LIBREWOLF_UBO_ASSETS_URL:-$DEFAULT_SOURCE_URL}"
OUTPUT_PATH="${LIBREWOLF_UBO_LISTS_OUTPUT:-$DEFAULT_OUTPUT_PATH}"

tmp_assets="$(mktemp)"
tmp_output="$(mktemp)"
cleanup() {
  if [[ -n ${tmp_assets:-} ]]; then
    rm -f "$tmp_assets"
  fi
  if [[ -n ${tmp_output:-} ]]; then
    rm -f "$tmp_output"
  fi
}
trap cleanup EXIT

curl -fsSL --retry 3 --max-time 30 "$SOURCE_URL" -o "$tmp_assets"

jq --arg source "$SOURCE_URL" '
  {
    _comment: "Generated by .github/scripts/update-librewolf-ubo-lists.sh. Do not edit by hand.",
    source: $source,
    lists: [
      to_entries[]
      | select(.value.content == "filters")
      | select((.value.off // false) != true)
      | .key
    ]
  }
' "$tmp_assets" >"$tmp_output"

jq --exit-status '
  .lists | type == "array" and length > 0
' "$tmp_output" >/dev/null

mkdir -p "$(dirname "$OUTPUT_PATH")"
mv "$tmp_output" "$OUTPUT_PATH"
tmp_output=""
