#!/usr/bin/env bash
# Refresh the generated uBO list selection from LibreWolf's upstream asset catalog.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE_URL="https://codeberg.org/librewolf/source/raw/branch/main/assets/uBOAssets.json"
OUTPUT_PATH="${REPO_ROOT}/modules/browsers/_librewolf-ubo-default-lists.json"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

curl -fsSL --retry 3 --max-time 30 "$SOURCE_URL" | jq --tab --arg source "$SOURCE_URL" '
  [to_entries[] | select(.value.content == "filters" and .value.off != true) | .key]
  | if length == 0 then error("no enabled filter lists found") else . end
  | {
      _comment: "Generated by .github/scripts/update-librewolf-ubo-lists.sh. Do not edit by hand.",
      source: $source,
      lists: .
    }
' >"$tmp"

mv "$tmp" "$OUTPUT_PATH"
