excludes = [
  "inputs/*",
  ".pre-commit-config.yaml",
  "nixos-manual/*",
  "*.lock",
  "*.patch",
  "package-lock.json",
  "go.mod",
  "go.sum",
  ".gitattributes",
  ".gitignore",
  ".gitmodules",
  ".hgignore",
  ".svnignore",
  "LICENSE",
]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = [
  "*.js",
  "*.cjs",
  "*.mjs",
  "*.ts",
  "*.jsx",
  "*.tsx",
  "*.json",
  "*.jsonc",
  "*.css",
  "*.graphql",
  "*.gql",
  "*.html",
  "*.vue",
  "*.svelte",
  "*.astro",
]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-w", "-i", "2", "-s"]
