/*
  Package: brave
  Description: Privacy-focused Chromium-based browser configured with managed policies.
  Homepage: https://brave.com/
  Documentation: https://support.brave.app/hc/en-us/articles/360039248271-Group-Policy
  Repository: https://github.com/brave/brave-browser

  Summary:
    * Installs Brave with managed policies for privacy, telemetry reduction, and feature cleanup.
    * Keeps Brave Shields content blocking enabled while disabling telemetry-heavy Brave features.

  Options:
    --incognito: Launch Brave directly in a private browsing session.
    brave://policy: Inspect the active managed policy set after rebuild.
    /etc/brave/policies/managed/extended.json: Managed policy file generated by this module.
    --enable-features=VaapiVideoDecoder,VaapiVideoEncoder: Enable VA-API hardware acceleration on supported GPUs.
    --disable-features=OutdatedBuildDetector: Suppress Brave's self-update prompts when using the wrapped build.
    --ozone-platform-hint=auto: Allow Brave to negotiate Wayland or X11 automatically on Linux systems.

  Notes:
    * Brave policy keys were checked against Brave policy_templates.zip VERSION 147.1.91.88.
*/
_:
let
  BraveModule =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.programs.brave.extended;

      # Kagi default search provider, shared verbatim with google-chrome and
      # ungoogled-chromium so every Chromium-family browser stays symmetric.
      inherit (import ../_chromium-policies.nix) managedDefaultSearchProvider;

      defaultManagedPolicies = {
        # Brave product features and promotions.
        BraveAIChatEnabled = false;
        BraveNewsDisabled = true;
        BravePlaylistEnabled = false;
        BraveRewardsDisabled = true;
        BraveSpeedreaderEnabled = false;
        BraveTalkDisabled = true;
        BraveVPNDisabled = true;
        BraveWalletDisabled = true;
        BraveWaybackMachineEnabled = false;
        TorDisabled = true;

        # Brave telemetry, analytics, discovery, and feedback.
        BraveP3AEnabled = false;
        BraveStatsPingEnabled = false;
        BraveWebDiscoveryEnabled = false;
        BrowserNetworkTimeQueriesEnabled = false;
        FeedbackSurveysEnabled = false;
        MetricsReportingEnabled = false;
        UrlKeyedAnonymizedDataCollectionEnabled = false;
        UserFeedbackAllowed = false;

        # Brave privacy protections.
        BraveDebouncingEnabled = true;
        BraveDeAmpEnabled = true;
        BraveGlobalPrivacyControlEnabled = true;
        BraveReduceLanguageEnabled = true;
        BraveTrackingQueryParametersFilteringEnabled = true;
        DefaultBraveAdblockSetting = 2;
        DefaultBraveFingerprintingV2Setting = 3;
        DefaultBraveHttpsUpgradeSetting = 2;
        DefaultBraveReferrersSetting = 2;
        DefaultBraveRemember1PStorageSetting = 2;

        # Sync/sign-in.
        BrowserSignin = 0;
        SigninInterceptionEnabled = false;
        SyncDisabled = true;

        # Password manager, passkeys, autofill, and import surfaces.
        AutofillAddressEnabled = false;
        AutofillCreditCardEnabled = false;
        AutofillPredictionSettings = 2;
        ImportAutofillFormData = false;
        ImportSavedPasswords = false;
        PasswordLeakDetectionEnabled = false;
        PasswordManagerEnabled = false;
        PasswordManagerPasskeysEnabled = false;
        PasswordSharingEnabled = false;

        # Search, suggestions, prediction, field trials, and background lookups.
        AlternateErrorPagesEnabled = false;
        ChromeVariations = 1;
        DomainReliabilityAllowed = false;
        NetworkPredictionOptions = 2;
        SearchSuggestEnabled = false;

        # Keep Standard Safe Browsing, but disable extra reporting/scanning paths.
        DisableSafeBrowsingProceedAnyway = true;
        SafeBrowsingDeepScanningEnabled = false;
        SafeBrowsingExtendedReportingEnabled = false;
        SafeBrowsingProtectionLevel = 1;
        SafeBrowsingProxiedRealTimeChecksAllowed = false;
        SafeBrowsingSurveysEnabled = false;

        # HTTPS, DNS, and WebRTC leakage controls.
        EncryptedClientHelloEnabled = true;
        HttpsOnlyMode = "force_enabled";
        HttpsUpgradesEnabled = true;
        WebRtcEventLogCollectionAllowed = false;
        WebRtcIPHandling = "disable_non_proxied_udp";
        WebRtcTextLogCollectionAllowed = false;

        # Google/Chromium AI integrations exposed by the current Brave template.
        AIModeSettings = 1;
        BuiltInAIAPIsEnabled = false;
        CreateThemesSettings = 2;
        DevToolsGenAiSettings = 2;
        GeminiSettings = 1;
        GenAILocalFoundationalModelSettings = 1;
        HelpMeWriteSettings = 2;
        HistorySearchSettings = 2;
        SearchContentSharingSettings = 1;
        TabCompareSettings = 2;

        # UI/features commonly considered clutter or promotion.
        BrowserLabsEnabled = false;
        DefaultBrowserSettingEnabled = false;
        DesktopSharingHubEnabled = false;
        EnableMediaRouter = false;
        GoogleSearchSidePanelEnabled = false;
        HistoryClustersVisible = false;
        NTPCardsVisible = false;
        NTPMiddleSlotAnnouncementVisible = false;
        NTPOutlookCardVisible = false;
        NTPSharepointCardVisible = false;
        PrivacySandboxPromptEnabled = false;
        ShoppingListEnabled = false;
        ShowFullUrlsInAddressBar = true;
        SideSearchEnabled = false;

        # Site permission defaults. Content setting value 2 generally means block.
        BlockThirdPartyCookies = true;
        DefaultClipboardSetting = 2;
        DefaultFileSystemReadGuardSetting = 2;
        DefaultFileSystemWriteGuardSetting = 2;
        DefaultGeolocationSetting = 2;
        DefaultIdleDetectionSetting = 2;
        DefaultInsecureContentSetting = 2;
        DefaultLocalFontsSetting = 2;
        DefaultNotificationsSetting = 2;
        DefaultPopupsSetting = 2;
        DefaultSensorsSetting = 2;
        DefaultSerialGuardSetting = 2;
        DefaultWebBluetoothGuardSetting = 2;
        DefaultWebHidGuardSetting = 2;
        DefaultWebUsbGuardSetting = 2;
        DefaultWindowManagementSetting = 2;

        # Disable online spellcheck/translate services.
        SpellCheckServiceEnabled = false;
        TranslateEnabled = false;
      }
      // managedDefaultSearchProvider;
    in
    {
      options.programs.brave.extended = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = "Whether to enable brave.";
        };

        package = lib.mkPackageOption pkgs "brave" { };

        enableManagedPolicies = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Whether to install Brave managed policies.";
        };

        managedPolicies = lib.mkOption {
          type = lib.types.attrs;
          default = defaultManagedPolicies;
          description = ''
            Brave enterprise policies written to /etc/brave/policies/managed.
          '';
        };
      };

      config = lib.mkIf cfg.enable {

        environment = {
          systemPackages = [ cfg.package ];

          etc = lib.mkIf cfg.enableManagedPolicies {
            "brave/policies/managed/extended.json".text = builtins.toJSON cfg.managedPolicies;
          };
        };
      };
    };
in
{
  nixpkgs.allowedUnfreePackages = [ "brave" ];
  flake.nixosModules.browsers.brave = BraveModule;
}
