# Expression generated by update.py; do not edit it by hand!
# NOTE: Local copy of the upstream PR https://github.com/NixOS/nixpkgs/pull/511131
# When that PR lands, replace this directory with `pkgs.brave-origin` in the
# overlay and rename this file to `_default.nix` per the custom-packages style
# guide.
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.91.102";

  allArchives = {
    aarch64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_arm64.deb";
      hash = "sha256-B36TV6azash2V1E4/uprY8diHekIo9oqDLvfePI5jKU=";
    };
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-L+0TRbmkTaM+QhYv2FnSM4OB7iqOqPSyi++J0dwRLPE=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
