# Expression generated by update.py; do not edit it by hand!
# TODO(https://github.com/NixOS/nixpkgs/pull/511131): replace this directory with `pkgs.brave-origin` in the
# overlay and rename this file to `_default.nix` per the custom-packages style
# guide.
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.94.56";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-QcQ6EW2LXyVMyJjogjthrpE7xsY3miXQnj1gXStWYWk=";
    };
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-v${version}-darwin-arm64.zip";
      hash = "sha256-18539un2F5OzlRTVytPuqraEC9SAmOShBAIuM0f0OCM=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
