# Expression generated by update.py; do not edit it by hand!
# TODO(https://github.com/NixOS/nixpkgs/pull/511131): replace this directory with `pkgs.brave-origin` in the
# overlay and rename this file to `_default.nix` per the custom-packages style
# guide.
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.93.33";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-F/50bPsWlyCnxOUqo4rrhtofXqgM1VG26cQ+HDsWxFk=";
    };
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-v${version}-darwin-arm64.zip";
      hash = "sha256-6JKW0jpn13egVB1eCVhUwVF3AHXpHkUPUITZL6D3W3I=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
