/*
  Package: patch
  Description: GNU utility for applying unified or context diff files to original sources.
  Homepage: https://www.gnu.org/software/patch/
  Documentation: https://www.gnu.org/software/patch/manual/
  Repository: https://git.savannah.gnu.org/cgit/patch.git

  Summary:
    * Reads diff files generated by tools like `diff` to update source trees safely.
    * Supports dry runs, fuzz factors, and automatic backup creation to aid collaborative development.

  Options:
    -p1: Strip one leading path component from filenames when applying patches.
    --dry-run: Preview changes without writing to disk, useful for validating patches.
    -R: Reverse an already-applied patch to restore the previous state.
*/

/*
  Package: patch
  Description: GNU utility for applying unified or context diff files to original sources.
  Homepage: https://www.gnu.org/software/patch/
  Documentation: https://www.gnu.org/software/patch/manual/
  Repository: https://git.savannah.gnu.org/cgit/patch.git

  Summary:
    * Reads diff files generated by tools like `diff` to update source trees safely.
    * Supports dry runs, fuzz factors, and automatic backup creation to aid collaborative development.

  Options:
    patch -p1 < file.patch: Apply a patch while stripping one leading path component.
    patch --dry-run < file.patch: Preview changes without writing to disk.
    patch -R < file.patch: Reverse an already-applied patch.
*/

{
  flake.nixosModules.apps.patch =
    { pkgs, ... }:
    {
      environment.systemPackages = [ pkgs.patch ];
    };
}
