# Lefthook RC file - sets up nix develop PATH for hooks
# Generated by Nix - do not edit directly

# Skip if already in nix shell (fast path)
if [ -n "${IN_NIX_SHELL:-}" ]; then
  return 0 2>/dev/null || true
fi

CACHE_DIR=".git/lefthook-cache"
CACHE_FILE="$CACHE_DIR/path.sh"
HASH_FILE="$CACHE_DIR/flake.lock.hash"

mkdir -p "$CACHE_DIR" 2>/dev/null || true

# Compute hash of flake.lock
current_hash=""
if [ -f "flake.lock" ]; then
  current_hash=$(sha256sum flake.lock 2>/dev/null | cut -d' ' -f1)
fi

# Check if cache is valid
needs_update=1
if [ -f "$CACHE_FILE" ] && [ -f "$HASH_FILE" ]; then
  cached_hash=$(cat "$HASH_FILE" 2>/dev/null || echo "")
  if [ "$current_hash" = "$cached_hash" ] && [ -n "$current_hash" ]; then
    needs_update=0
  fi
fi

# Generate cache if needed (slow first time, fast after)
if [ "$needs_update" = "1" ]; then
  echo "Generating lefthook environment cache..." >&2
  # Extract only PATH from nix develop (POSIX-compatible)
  nix_path=$(nix develop --accept-flake-config -c sh -c 'echo "$PATH"' 2>/dev/null)
  if [ -n "$nix_path" ]; then
    echo "export PATH=\"$nix_path\"" >"$CACHE_FILE"
    echo "$current_hash" >"$HASH_FILE"
    echo "Cache generated: $CACHE_FILE" >&2
  else
    echo "Warning: Failed to generate cache, hooks may fail outside devshell" >&2
    return 0 2>/dev/null || true
  fi
fi

# Source the cached PATH
if [ -f "$CACHE_FILE" ]; then
  . "$CACHE_FILE"
fi
