#!/usr/bin/env python3

"""Sync the firefoxpwa management-extension pin with the nixpkgs connector.

The PWAsForFirefox browser extension ships only through addons.mozilla.org (it
is not in the nixpkgs `firefoxpwa` output and is absent from upstream GitHub
release assets), and AMO download URLs require a per-version opaque file id that
cannot be derived from the version string. This script resolves that id from the
AMO API and writes it to `modules/browsers/_firefoxpwa-extension-pin.json`, which the
gecko extension policy reads to force-install the extension.

The connector (native messaging host) and extension stay protocol-compatible as
long as they share a major version: the upstream `checkNativeStatus` treats a
differing minor/patch as `update-minor` (compatible) and only a differing major
as `update-major` (incompatible). AMO does not publish every connector release
(for example 2.18.1/2.18.3/2.18.4 were skipped), so this resolver pins the
newest published extension whose major matches and whose version is at or below
the connector version, which yields an exact match when AMO has one.
"""

import argparse
import sys
import urllib.parse
from functools import cmp_to_key
from pathlib import Path
from typing import Any, cast


def _flake_root(start: Path) -> Path:
    """Walk up from ``start`` until ``flake.nix`` is found."""
    for parent in [start, *start.parents]:
        if (parent / "flake.nix").is_file():
            return parent
    msg = f"Could not find flake.nix above {start}"
    raise RuntimeError(msg)


FLAKE_ROOT = _flake_root(Path(__file__).resolve().parent)
sys.path.insert(0, str(FLAKE_ROOT / "scripts"))

from updater import fetch_json, load_hashes, save_hashes  # noqa: E402
from updater.nix import nix_command  # noqa: E402
from updater.version import compare_versions, parse_version  # noqa: E402

PIN_FILE = FLAKE_ROOT / "modules" / "browsers" / "_firefoxpwa-extension-pin.json"

# AMO addon GUID, matching `firefoxpwaExt` in _gecko-extension-data.nix. The API
# accepts the GUID, slug, or numeric id; the GUID is the stable identifier the
# policy installs under.
AMO_ADDON_ID = "firefoxpwa@filips.si"
AMO_VERSIONS_URL = (
    "https://addons.mozilla.org/api/v5/addons/addon/"
    + urllib.parse.quote(AMO_ADDON_ID, safe="")
    + "/versions/?page_size=50"
)

GENERATED_COMMENT = "Generated by scripts/update-firefoxpwa-extension.py. Do not edit by hand."


def connector_version() -> str:
    """Evaluate pkgs.firefoxpwa.version from the flake's locked nixpkgs."""
    # path: flakeref bypasses the git+file fetcher; a bare-path getFlake would
    # pull the private secrets submodule under self.submodules = true (Lix),
    # which this workflow's plain checkout cannot read.
    expr = (
        '(builtins.getFlake "path:'
        + str(FLAKE_ROOT)
        + '").inputs.nixpkgs.legacyPackages.${builtins.currentSystem}.firefoxpwa.version'
    )
    result = nix_command(
        [
            "eval",
            "--impure",
            "--raw",
            "--accept-flake-config",
            "--expr",
            expr,
        ],
    )
    return result.stdout.strip()


def fetch_amo_versions() -> list[dict[str, Any]]:
    """Fetch every published AMO version record, following pagination."""
    versions: list[dict[str, Any]] = []
    url: str | None = AMO_VERSIONS_URL
    while url:
        data = cast("dict[str, Any]", fetch_json(url))
        versions.extend(cast("list[dict[str, Any]]", data["results"]))
        url = cast("str | None", data.get("next"))
    return versions


def resolve_extension(versions: list[dict[str, Any]], package_version: str) -> dict[str, Any]:
    """Pick the newest AMO version with the connector's major, at or below it."""
    pkg_numeric, _ = parse_version(package_version)
    if not pkg_numeric:
        msg = f"Could not parse connector version {package_version!r}"
        raise RuntimeError(msg)
    pkg_major = pkg_numeric[0]

    candidates = [
        record
        for record in versions
        if (numeric := parse_version(cast("str", record["version"]))[0])
        and numeric[0] == pkg_major
        and compare_versions(cast("str", record["version"]), package_version) <= 0
    ]
    if not candidates:
        msg = (
            f"No AMO firefoxpwa extension with major {pkg_major} at or below "
            f"connector {package_version}; the connector may be newer than any "
            "published extension. See "
            "https://addons.mozilla.org/firefox/addon/pwas-for-firefox/"
        )
        raise RuntimeError(msg)

    return max(
        candidates,
        key=cmp_to_key(
            lambda a, b: compare_versions(cast("str", a["version"]), cast("str", b["version"])),
        ),
    )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--package-version",
        help="Override the connector version instead of evaluating it from the flake.",
    )
    return parser.parse_args()


def main() -> None:
    """Resolve and write the firefoxpwa extension pin."""
    args = parse_args()
    package_version = args.package_version or connector_version()
    record = resolve_extension(fetch_amo_versions(), package_version)
    extension_version = cast("str", record["version"])
    url = cast("str", cast("dict[str, Any]", record["file"])["url"])

    pin = {
        "_comment": GENERATED_COMMENT,
        "packageVersion": package_version,
        "extensionVersion": extension_version,
        "url": url,
    }

    print(f"Connector: {package_version}")
    print(f"Extension: {extension_version}")
    print(f"URL:       {url}")

    if PIN_FILE.exists() and load_hashes(PIN_FILE) == pin:
        print("Pin already up to date")
        return

    save_hashes(PIN_FILE, pin)
    print(f"Updated {PIN_FILE.relative_to(FLAKE_ROOT)}")


if __name__ == "__main__":
    main()
